name: ci

on:
  push:
    paths:
      - "**.m"
  pull_request:
  release:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get update -y
        sudo apt-get install -yq --no-install-suggests --no-install-recommends octave > /dev/null
    - run: octave --eval "test_matlab(); exit"
      working-directory: tests
